-- Create raw telemetry table

USE DATABASE TESLA_TELEMETRY_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS TESLA_TELEMETRY_RAW (
    VEHICLE_ID VARCHAR(50),
    EVENT_TIMESTAMP TIMESTAMP_TZ,
    SPEED FLOAT,
    BATTERY_LEVEL FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create curated telemetry table

USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS TESLA_TELEMETRY (
    VEHICLE_ID VARCHAR(50) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_TZ NOT NULL,
    SPEED FLOAT,
    BATTERY_LEVEL FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
