-- Curated analytical model for Tesla telemetry

USE DATABASE TESLA_TELEMETRY_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW TESLA_TELEMETRY_SUMMARY AS
SELECT
    VEHICLE_ID,
    COUNT(*) AS TOTAL_EVENTS,
    ROUND(AVG(SPEED), 2) AS AVG_SPEED,
    ROUND(MAX(SPEED), 2) AS MAX_SPEED,
    ROUND(AVG(BATTERY_LEVEL), 2) AS AVG_BATTERY_LEVEL,
    ROUND(MIN(BATTERY_LEVEL), 2) AS MIN_BATTERY_LEVEL,
    MIN(EVENT_TIMESTAMP) AS FIRST_EVENT_TIME,
    MAX(EVENT_TIMESTAMP) AS LAST_EVENT_TIME
FROM TESLA_TELEMETRY
GROUP BY VEHICLE_ID;
